### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by nrempel** [adonisjs/adonis-redis#1]
Add feedback when connection config is invalid. Currently, it just hangs indefinitely without feedback which makes it hard to debug.

Possibly add a timeout to the connection and fail with an error?

**Comment by thetutlage** [comment]
You can do

```
Redis.on('error', function (error) {

})
```

Docs for events http://adonisjs.com/docs/3.1/redis#_lifecycle_events

**Comment by thetutlage** [comment]
Closing
