### ISSUE TITLE
Client connections not closing

### ISSUE THREAD

**Issue by moraleslevi** [adonisjs/adonis-redis#15]
I'm having some issues with an Adonis application that is using Redis (3.0) for both sessions and caching. The application recently produced an error from Redis: `ERR max number of clients reached`.

Upon looking into the issue I noticed that any new connection to Redis from the Adonis Application (which appears to be every HTTP Request) doesn't appear to be getting disconnected. This resulted in an ever increasing number of clients+connections eventually hitting my configured limit of 1024. I was able to increase the `maxclients` setting to temporarily restore the application.

I'm curious if there is something that I'm missing here or if this is the expected behavior? It could very well be a Redis configuration issue on my part but Redis documentation seems to lay the blame for too many connections on the application-side not properly disconnecting old clients.

Any insight would be much appreciated. Thanks.

**Comment by thetutlage** [comment]
Hard to tell anything without seeing any code

**Comment by moraleslevi** [comment]
After digging into it some more. It seems like this may be an issue with adonis-session instead. I'm seeing two issues.

Here is my redis.js config:

```
const Env = use('Env')

module.exports = {
  connection: Env.get('REDIS_CONNECTION', 'local'),

  local: {
    host: Env.get('REDIS_HOST', process.env.DATA_REDIS_HOST),
    port: Env.get('REDIS_PORT', 6379),
    password: Env.get('REDIS_PASSWORD', null),
    db: 0,
    keyPrefix: 'ph',
    connectionName: 'primary' // this was set to help debug
  }
}
```

1. I'm unable to set the redis session configuration using `redis: 'self::redis.local'`.

It gives me this error, which seems like it's not getting the appropriate connection information.

```
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
```

2. If I copy the `local` redis configuration into the session.js config it works, but every HTTP request results in a new redis connection, instead of using the existing connection setup by Redis.

The issue I'm experiencing is likely not an issue with connections not disconnecting, but rather the session driver not re-using the existing redis connection. This is causing the creation of new connections and ultimately hitting the configured maxclients on redis itself.

**Comment by thetutlage** [comment]
You are right. I am pushing a fix in this and session module both.

This commit https://github.com/adonisjs/adonis-redis/commit/a2c527bbc651d2ad48fe8e9bfbe6027decfe5f5f will make it easier to add connections to the pool by giving them a name.

**Comment by thetutlage** [comment]
Related commit ids

https://github.com/adonisjs/adonis-session/commit/cc0744a45ae3f058a4c6e67bad2094b425dba19f
https://github.com/adonisjs/adonis-redis/commit/9a891c50c9499e209c08d57cbf8b8ca347820e22

Can you please try by updating `adonis-redis` to `2.0.6` and trying `adonis-session` from github develop branch?

**Comment by moraleslevi** [comment]
This appears to resolve the issue. I'm only seeing two redis connections now (cache + session) which is what I expected.

Thanks for the quick response and resolution!

**Comment by thetutlage** [comment]
Nice, will publish adonis-session to npm in a while
