### ISSUE TITLE
start/redis.js seems not booted/registered.

### ISSUE THREAD

**Issue by iedmrc** [adonisjs/adonis-redis#17]
## Package version
    "@adonisjs/redis": "^2.0.7"

## Node.js and npm version
Node: v10.8.0
Npm:6.4.1

## Sample Code (to reproduce the issue)
```
Redis.subscribe('news',async (msg) => {
  console.log(msg)
});
```

The start/redis.js file which copied from https://github.com/adonisjs/adonis-redis/blob/develop/examples/listener.js seems not booted by default. Because for example if I uncomment 
```
Redis.subscribe('news',async (msg) => {
  console.log(msg)
});
```
this piece of code, and publish a message from redis-cli to `news` channel, nothing happens and redis returns 0 which means channel has no subscriber. 
If I copy the code above to event.js, It works as expected. Do I have to register/boot manually the redis.js (listener) file ? I think It should be registered/booted by default. Or am I missing something else? 
Thanks!

**Comment by thetutlage** [comment]
The file should be copied to `start/events.js` as mentioned in the docs https://adonisjs.com/docs/4.0/redis#_pub_sub.

I will push a fix soon

**Comment by ahmadarif** [comment]
I have copied `start/redis.js` to `start/events.js` but still not working. And then downgrade to version `^2.0.4` to fixed this issue.
